name: "Lint"
permissions: "read-all"
on:
  - "push"
  - "pull_request"

jobs:
  formatting:
    name: "Formatting"
    runs-on: "ubuntu-slim"
    steps:
      - name: "Install Haxe"
        uses: "krdlab/setup-haxe@v2"
        with:
          haxe-version: "4.3.7"
      - name: "Get Haxelib local repository path"
        id: "haxelib-get-path"
        shell: "bash"
        run: |
          echo "dir=$(haxelib config)" >> $GITHUB_OUTPUT
      - name: "Checkout"
        uses: "actions/checkout@v6"
      - name: "Restore cached Haxe tools"
        id: "restore-cache"
        uses: "actions/cache/restore@v5"
        with:
          path: "${{ steps.haxelib-get-path.outputs.dir }}"
          key: "haxelib-repo-formatter-1.18.0"
      - name: "Install Haxe tools"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: "haxelib install formatter 1.18.0 --quiet"
      - name: "Cache Haxe tools"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: "actions/cache/save@v5"
        with:
          path: "${{ steps.haxelib-get-path.outputs.dir }}"
          key: "haxelib-repo-formatter-1.18.0"
      - name: "Run formatter"
        run: "haxelib run formatter --check --source src"

  checkstyle:
    name: "Static analysis"
    runs-on: "ubuntu-slim"
    steps:
      - name: "Install Haxe"
        uses: "krdlab/setup-haxe@v2"
        with:
          haxe-version: "4.3.7"
      - name: "Get Haxelib local repository path"
        id: "haxelib-get-path"
        shell: "bash"
        run: |
          echo "dir=$(haxelib config)" >> $GITHUB_OUTPUT
      - name: "Checkout"
        uses: "actions/checkout@v6"
      - name: "Restore cached Haxe tools"
        id: "restore-cache"
        uses: "actions/cache/restore@v5"
        with:
          path: "${{ steps.haxelib-get-path.outputs.dir }}"
          key: "haxelib-repo-checkstyle-2.9.0"
      - name: "Install tools"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: "haxelib install checkstyle 2.9.0 --quiet"
      - name: "Cache Haxe tools"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: "actions/cache/save@v5"
        with:
          path: "${{ steps.haxelib-get-path.outputs.dir }}"
          key: "haxelib-repo-checkstyle-2.9.0"
      - name: "Run Checkstyle"
        run: "haxelib run checkstyle --show-parser-errors --exitcode --source src"
