name: "Test"
permissions: "read-all"
on:
  - "push"
  - "pull_request"

jobs:
  build:
    name: "Build suite (with Haxe ${{ matrix.haxe-version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        haxe-version:
          - "4.2.0"
          - "4.2.5"
          - "4.3.0"
          - "4.3.7"
          - "latest"
    steps:
      - name: "Install Haxe"
        uses: "krdlab/setup-haxe@v1"
        with:
          haxe-version: "${{ matrix.haxe-version }}"
      - name: "Get Haxelib local repository path"
        id: "haxelib-get-path"
        shell: "bash"
        run: |
          echo "dir=$(haxelib config)" >> $GITHUB_OUTPUT
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          lfs: false
      - name: "Restore cached Haxe dependencies"
        id: "restore-cache"
        uses: "actions/cache/restore@v4"
        with:
          path: "${{ steps.haxelib-get-path.outputs.dir }}"
          key: "haxelib-repo-${{ matrix.haxe-version }}-${{ hashFiles('tests/buildTests.hxml') }}"
          restore-keys: |
            haxelib-repo-${{ matrix.haxe-version }}-
            haxelib-repo-
      - name: "Install Haxe dependencies"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        shell: "bash"
        run: "haxelib install tests/buildTests.hxml --always --quiet"
      - name: "Cache Haxe dependencies"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: "actions/cache/save@v4"
        with:
          path: "${{ steps.haxelib-get-path.outputs.dir }}"
          key: "haxelib-repo-${{ matrix.haxe-version }}-${{ hashFiles('tests/buildTests.hxml') }}"
      - name: "Build tests"
        working-directory: "tests"
        shell: "bash"
        run: "haxe buildTests.hxml"
        env:
          OCAMLRUNPARAM: "b"
      - name: "Upload built suites"
        uses: "actions/upload-artifact@v4"
        with:
          name: "suites-${{ matrix.haxe-version }}"
          path: "tests/out/"
          retention-days: 1

  hashlink:
    name: "Hashlink ${{ matrix.hl-version }} (built with ${{ matrix.haxe-version }}, Windows)"
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        hl-version:
          - "1.15.0"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: "Install Hashlink"
        uses: "cedx/setup-hashlink@v6"
        with:
          version: "${{ matrix.hl-version }}"
      - name: "Download test suites"
        uses: "actions/download-artifact@v4"
        with:
          name: "suites-${{ matrix.haxe-version }}"
      - name: "Run test suite"
        shell: "bash"
        run: "hl hashlink/suite.hl"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-hashlink-${{ matrix.hl-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "coverage-hashlink-${{ matrix.hl-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  java:
    name: "Java ${{ matrix.java-version }} (built with ${{ matrix.haxe-version }}, Linux)"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "23"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: "Install Java"
        uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java-version }}"
      - name: "Download test suites"
        uses: "actions/download-artifact@v4"
        with:
          name: "suites-${{ matrix.haxe-version }}"

      - name: "Run test suite"
        shell: "bash"
        run: "java -jar java/suite.jar"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-java-${{ matrix.java-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "coverage-java-${{ matrix.java-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  lua:
    name: "Lua ${{ matrix.lua-version }} (built with ${{ matrix.haxe-version }}, Linux)"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        lua-version:
          - "5.1"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: "Install Lua"
        uses: "leafo/gh-actions-lua@v11"
        with:
          luaVersion: "${{ matrix.lua-version }}"
          buildCache: false
      - name: "Install Luarocks"
        uses: "leafo/gh-actions-luarocks@v5"
      - name: "Install Lua dependencies"
        shell: "bash"
        run: |
          sudo apt-get install libpcre3-dev && \
          luarocks install hx-lua-simdjson && \
          luarocks install lrexlib-pcre2 && \
          luarocks install lrexlib-pcre && \
          luarocks install luasocket && \
          luarocks install luv && \
          luarocks install bit32
      - name: "Download test suites"
        uses: "actions/download-artifact@v4"
        with:
          name: "suites-${{ matrix.haxe-version }}"
      - name: "Run test suite"
        shell: "bash"
        run: "lua lua/suite.lua"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-lua-${{ matrix.lua-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "coverage-lua-${{ matrix.lua-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  nodejs:
    name: "Node.js ${{ matrix.node-version }} (built with ${{ matrix.haxe-version }}, Linux)"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "22"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: "Install Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "${{ matrix.node-version }}"
      - name: "Download test suites"
        uses: "actions/download-artifact@v4"
        with:
          name: "suites-${{ matrix.haxe-version }}"
      - name: "Run test suite"
        shell: "bash"
        run: "node nodejs/suite.js"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-nodejs-${{ matrix.node-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "coverage-nodejs-${{ matrix.node-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  coverage:
    name: "Process code coverage results"
    runs-on: "ubuntu-latest"
    needs:
      - "hashlink"
      - "java"
      - "lua"
      - "nodejs"
    steps:
      - name: "Checkout (for additional metadata)"
        uses: "actions/checkout@v4"
      - name: "Download coverage stats from the artifacts"
        uses: "actions/download-artifact@v4"
        with:
          pattern: "coverage-*"
          merge-multiple: true
      - name: "Upload code coverage report to Codecov"
        uses: "codecov/codecov-action@v5"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
          disable_search: false
          files: "lcov*.info"
          fail_ci_if_error: true
