name: "Test"
permissions: "read-all"
on:
  - "push"
  - "pull_request"

jobs:
  build:
    name: "Build suite (with Haxe ${{ matrix.haxe-version }})"
    runs-on: "ubuntu-slim"
    strategy:
      fail-fast: false
      matrix:
        haxe-version:
          - "4.2.0"
          - "4.2.5"
          - "4.3.0"
          - "4.3.7"
          - "latest"
    steps:
      - name: "Install Haxe"
        uses: "krdlab/setup-haxe@v2"
        with:
          haxe-version: "${{ matrix.haxe-version }}"
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          lfs: false
      - name: Install Haxe dependencies
        shell: bash
        run: haxelib install tests/buildTests.hxml --always --quiet
      - name: Apply additional config (Haxe 5 only)
        if: "${{ matrix.haxe-version == 'latest' }}"
        working-directory: tests
        shell: bash
        run: sed --in-place '1i--define haxe5' buildTests.hxml
      - name: "Build tests"
        working-directory: "tests"
        shell: "bash"
        run: "haxe buildTests.hxml"
        env:
          OCAMLRUNPARAM: "b"
      - name: "Upload built suites"
        uses: "actions/upload-artifact@v7"
        with:
          name: "suites-${{ matrix.haxe-version }}"
          path: "tests/out/"
          retention-days: 1

  hashlink:
    name: "Hashlink ${{ matrix.hl-version }} (built with ${{ matrix.haxe-version }}, Windows)"
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        hl-version:
          - "1.14.0"
          - "1.15.0"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: "Install Hashlink"
        uses: "cedx/setup-hashlink@v8"
        with:
          version: "${{ matrix.hl-version }}"
      - name: "Download test suites"
        uses: "actions/download-artifact@v8"
        with:
          name: "suites-${{ matrix.haxe-version }}"
      - name: "Run test suite"
        shell: "bash"
        run: "hl hashlink/suite.hl"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-hashlink-${{ matrix.hl-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v7"
        with:
          name: "coverage-hashlink-${{ matrix.hl-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  java:
    name: "Java ${{ matrix.java-version }} (built with ${{ matrix.haxe-version }}, Linux)"
    runs-on: "ubuntu-slim"
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "11"
          - "25"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: "Install Java"
        uses: "actions/setup-java@v5"
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java-version }}"
      - name: "Download test suites"
        uses: "actions/download-artifact@v8"
        with:
          name: "suites-${{ matrix.haxe-version }}"

      - name: "Run test suite"
        shell: "bash"
        run: "java -jar java/suite.jar"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-java-${{ matrix.java-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v7"
        with:
          name: "coverage-java-${{ matrix.java-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  lua:
    name: Lua ${{ matrix.lua-version }} (built with ${{ matrix.haxe-version }}, Linux)
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        lua-version:
          - "5.1"
          - "luajit-2.1"
          - "5.2"
          - "5.4"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: Update Ubuntu repositories
        run: sudo apt-get update
      - name: "Install Lua"
        uses: "leafo/gh-actions-lua@v12"
        with:
          luaVersion: "${{ matrix.lua-version }}"
          buildCache: false
      - name: "Install Luarocks"
        uses: "leafo/gh-actions-luarocks@v6"
      - name: Install Ubuntu packages
        shell: bash
        run: sudo apt-get install cmake libpcre2-dev libpcre3-dev
      - name: "Install Lua dependencies"
        shell: "bash"
        run: |
          luarocks install hx-lua-simdjson && \
          luarocks install lrexlib-pcre2 && \
          luarocks install lrexlib-pcre && \
          luarocks install luasocket && \
          luarocks install luautf8 && \
          luarocks install luv
      - name: Install Lua dependencies (bit32)
        if: "${{ matrix.lua-version != '5.2' }}"
        shell: bash
        run: luarocks install bit32
      - name: "Download test suites"
        uses: "actions/download-artifact@v8"
        with:
          name: "suites-${{ matrix.haxe-version }}"
      - name: "Run test suite"
        shell: "bash"
        run: "lua lua/suite.lua"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-lua-${{ matrix.lua-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v7"
        with:
          name: "coverage-lua-${{ matrix.lua-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  nodejs:
    name: "Node.js ${{ matrix.node-version }} (built with ${{ matrix.haxe-version }}, Linux)"
    runs-on: "ubuntu-slim"
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "20"
          - "24"
        haxe-version:
          - "4.2.0"
          - "4.3.7"
          - "latest"
    needs:
      - "build"
    steps:
      - name: "Install Node.js"
        uses: "actions/setup-node@v6"
        with:
          node-version: "${{ matrix.node-version }}"
      - name: "Download test suites"
        uses: "actions/download-artifact@v8"
        with:
          name: "suites-${{ matrix.haxe-version }}"
      - name: "Run test suite"
        shell: "bash"
        run: "node nodejs/suite.js"
      - name: "Name coverage stats"
        shell: "bash"
        run: "mv lcov.info lcov-nodejs-${{ matrix.node-version }}-${{ matrix.haxe-version }}.info"
      - name: "Save coverage stats as an artifact"
        uses: "actions/upload-artifact@v7"
        with:
          name: "coverage-nodejs-${{ matrix.node-version }}-${{ matrix.haxe-version }}"
          path: "lcov*.info"
          if-no-files-found: "error"
          retention-days: 1

  coverage:
    name: "Process code coverage results"
    runs-on: "ubuntu-slim"
    needs:
      - "hashlink"
      - "java"
      - "lua"
      - "nodejs"
    steps:
      - name: "Checkout (for additional metadata)"
        uses: "actions/checkout@v6"
      - name: "Download coverage stats from the artifacts"
        uses: "actions/download-artifact@v8"
        with:
          pattern: "coverage-*"
          merge-multiple: true
      - name: "Upload code coverage report to Codecov"
        uses: "codecov/codecov-action@v6"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
          disable_search: false
          files: "lcov*.info"
          fail_ci_if_error: true
